services:
  
  proxy:
    image: docker.io/nginx:${NGINX_IMAGE}
    container_name: proxy
    restart: unless-stopped
    ports:
      - "${PROXY_HTTP_PORT}:80"
      - "${PROXY_HTTPS_PORT}:443"
      - "${EXPLORER_PORT}:8443"
      - "${GRAFANA_PORT}:3443"
      - "${INFLUXDB_PORT}:8181"
      # Optional for Versity S3 Gateway access
      # - "${S3_PORT}:7070"
    volumes:
      - ./certs/proxy/ca.crt:/etc/nginx/ssl/ca.crt:ro
      - ./certs/proxy/external/pub_ca.crt:/etc/nginx/ssl/pub_ca.crt:ro
      - ./certs/proxy/external/server.crt:/etc/nginx/ssl/server.crt:ro
      - ./certs/proxy/external/server.key:/etc/nginx/ssl/server.key:ro
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro
      
      # ssl_ecdh_curve X25519MLKEM768; use PQC - https://github.com/nginx/nginx/issues/288      
    networks:
      epa:
        ipv4_address: ${PROXY_IP}

  influxdb:
    container_name: epa4-influxdb
    image: epa/influxdb:${INFLUXDB3_VERSION}
    restart: unless-stopped
    build:
      context: .
      dockerfile: influxdb/Dockerfile
      args:
        INFLUXDB3_BUILD_VERSION: ${INFLUXDB3_BUILD_VERSION}
    ports:
      - "${INFLUXDB_PORT}:8181"
      # Port 8182 (admin token recovery) is NOT exposed externally for security
      # It's only accessible within the Docker network for internal token generation
    environment:
      # Removed S3-related environment variables since we're using local file storage
      TLS_KEY: /home/influx/certs/influxdb.key
      TLS_CERT: /home/influx/certs/influxdb.crt
      TLS_MIN_VERSION: tls-1.3
      INFLUXDB3_TLS_CA: /home/influx/certs/ca.crt
      TLS_CA: /home/influx/certs/ca.crt
      NODE_ID: ${INFLUXDB_NODE_ID}
      INFLUXDB3_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      TOKEN_FILE: /home/influx/tokens/epa.token
      # Disable anonymous usage analytics (InfluxDB3 specific)
      INFLUXDB3_TELEMETRY_DISABLE_UPLOAD: ${INFLUXDB3_TELEMETRY_DISABLE_UPLOAD}    
    volumes:
      - ./data/influxdb:/var/lib/influxdb3
      - ./certs/influxdb/influxdb.crt:/home/influx/certs/influxdb.crt:ro
      - ./certs/influxdb/influxdb.key:/home/influx/certs/influxdb.key:ro
      - ./certs/influxdb/ca.crt:/home/influx/certs/ca.crt:ro
      - ./data/influxdb_tokens:/home/influx/tokens
    # Removed S3 dependency since we're using local file storage
    entrypoint: ["/home/influx/entrypoint.sh"]
    command: []
    networks:
      epa:
        ipv4_address: ${INFLUXDB_IP}

  collector:
    image: epa/collector:${COLLECTOR_VERSION}
    build:
      context: app
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
        PYTHON_DIGEST: ${PYTHON_DIGEST}
    # container_name: collector
    restart: unless-stopped
    command: ["--no-instrumenting"]
    environment:
      INFLUX_HOST: ${INFLUXDB_HOST:-influxdb}
      INFLUX_PORT: ${INFLUXDB_PORT}
      INFLUX_DB: ${INFLUXDB_DB}
      INFLUXDB3_AUTH_TOKEN_FILE: /home/app/tokens/epa.token
      INFLUXDB3_TLS_CA: /home/app/certs/ca.crt
      CA_CHAIN: /home/app/certs/ca.crt,/home/app/certs/influxdb_ca.crt      
      API: ${API}
      USERNAME: ${SANTRICITY_USERNAME}
      PASSWORD: ${SANTRICITY_PASSWORD}
    depends_on:
      - influxdb
    volumes:
      - ./certs/collector:/home/app/certs:ro
      - ./data/influxdb_tokens/epa.token:/home/app/tokens/epa.token:ro
      - ./data/samples/in:/home/app/samples/in:rw
      - ./data/samples/out:/home/app/samples/out:rw
    networks:
      epa:
        ipv4_address: ${EPA_COLLECTOR}

  utils:
    image: epa/utils:${COLLECTOR_VERSION}
    build:
      context: ./utils
    container_name: utils
    restart: "no"
    environment:
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_KEY}
      S3_ENDPOINT: https://s3:7070
      BUCKET: ${S3_BUCKET}
      CRED_DIR: /influxdb_credentials
      # InfluxDB3 Environment Variables
      INFLUX_HOST: influxdb
      INFLUX_PORT: ${INFLUXDB_PORT:-8181}
      INFLUX_DB: ${INFLUXDB_DB:-epa}
      INFLUXDB3_TLS_CA: /home/influx/ca.crt
      INFLUXDB3_AUTH_TOKEN_FILE: /home/influx/epa.token
    networks:
      epa:
        ipv4_address: ${UTILS_IP}
    volumes:
      - ./certs/_master/ca.crt:/home/influx/certs/ca.crt:ro
      - ./certs/influxdb/influxdb.crt:/home/influx/certs/influxdb.crt:ro
      - ./data/influxdb_tokens/epa.token:/home/influx/epa.token:ro
    command: ["tail","-f","/dev/null"]

  influx-mcp:
    image: epa/influxdb-mcp:${INFLUXDB_MCP_VERSION:-latest}
    build:
      context: .
      dockerfile: influx-mcp/Dockerfile
    container_name: influx-mcp
    restart: "no"
    environment:
      # InfluxDB3 Environment Variables
      # INFLUX_HOST: ${INFLUXDB_HOST:-influxdb}
      # INFLUX_PORT: ${INFLUXDB_PORT}
      INFLUX_DB: ${INFLUXDB_DB}
      INFLUX_DB_INSTANCE_URL: https://${INFLUXDB_HOST}:${INFLUXDB_PORT}
      INFLUXDB3_TLS_CA: /etc/ssl/certs/ca.crt
      INFLUXDB3_AUTH_TOKEN_FILE: /home/influxd/epa.token
      INFLUX_DB_PRODUCT_TYPE: core
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca.crt
      SSL_CERT_FILE:       /etc/ssl/certs/server.crt
      SSL_KEY_FILE:        /etc/ssl/private/server.key
    volumes:
      - ./certs/_master/ca.crt:/etc/ssl/certs/ca.crt:ro
      - ./certs/mcp/server.crt:/etc/ssl/certs/server.crt:ro
      - ./certs/mcp/server.key:/etc/ssl/private/server.key:ro
    networks:
      epa:
        ipv4_address: ${INFLUX_MCP_IP}
  grafana:
    image: epa/grafana:latest
    # Until 12.2 with custom CA bug is resolved, use own build from the main branch
    # image: docker.io/grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:3000" # HTTPS only
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      # HTTPS Configuration
      GF_SERVER_PROTOCOL: https
      GF_SERVER_CERT_FILE: /etc/grafana/certs/grafana.crt
      GF_SERVER_CERT_KEY: /etc/grafana/certs/grafana.key
      # Trust custom CA for InfluxDB connections
      GF_SERVER_ROOT_URL: https://localhost:${GRAFANA_PORT}
      # Workaround for Grafana 12.1 custom CA bug
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "false"
      GF_DATABASE_SSL_MODE: "disable"
      GF_PLUGIN_ENABLE_ALPHA: "true"
    volumes:
      - ./certs/_master/ca.crt:/usr/local/share/ca-certificates/ca.crt:ro
      - ./certs/grafana:/etc/grafana/certs:ro
      - ./data/grafana/storage:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      epa:
        ipv4_address: ${GRAFANA_IP}

  explorer:
    image: epa/influxdb3-explorer:${INFLUXDB3_EXPLORER_VERSION}
    build:
      context: .
      dockerfile: explorer/Dockerfile
      args:
        INFLUXDB3_EXPLORER_VERSION: ${INFLUXDB3_EXPLORER_VERSION}
    container_name: influxdb3-explorer
    restart: unless-stopped
    ports:
      - "${EXPLORER_PORT}:443"
      # - "8080:80" # For non-TLS access (not recommended)
    environment:
      SSL_CERT_PATH: /etc/nginx/ssl/cert.pem
      SSL_KEY_PATH: /etc/nginx/ssl/key.pem
      DATABASE_URL: /db/sqlite.db
      NODE_ENV: production
    command:
      - "--mode=admin"
    volumes:
      - ./data/explorer/db:/db:rw
      - ./data/explorer/config:/app-root/config:ro
      # InfluxDB Explorer's TLS certificates (expects cert.pem and key.pem)
      - ./certs/explorer:/etc/nginx/ssl:ro
      - ./certs/explorer/ca.crt:/usr/local/share/ca-certificates/ca.crt:ro
    depends_on:
      - influxdb
    networks:
      epa:
        ipv4_address: ${EXPLORER_IP}

networks:
  epa:
    ipam:
      config:
        - subnet: ${EPA_SUBNET}
