---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  namespace: epa
data:
  grafana.ini: |
    [server]
      protocol = http
      http_port = 3000
    [analytics]
      reporting_enabled = false
      check_for_updates = false
    [log]
      mode = console
      level = info
    [paths]
      data         = /var/lib/grafana/data
      logs         = /var/log/grafana
      plugins      = /var/lib/grafana/plugins
      provisioning = /etc/grafana/provisioning

