---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: epa
  labels:
    app: influxdb
    component: "database"
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: influxdb-creds
        image: docker.io/influxdb:1.8
        name: influxdb
        volumeMounts:
        - mountPath: /var/lib/influxdb/data
          name: var-lib-influxdb-data
        - mountPath: /var/lib/influxdb/wal
          name: var-lib-influxdb-wal
        - mountPath: /var/lib/influxdb/meta
          name: var-lib-influxdb-meta
      volumes:
      - name: var-lib-influxdb-data
        persistentVolumeClaim:
          claimName: influxdb-data-pvc
      - name: var-lib-influxdb-wal
        persistentVolumeClaim:
          claimName: influxdb-wal-pvc
      - name: var-lib-influxdb-meta
        persistentVolumeClaim:
          claimName: influxdb-meta-pvc

