services:

  influxdb:
    image: influxdb:1.11.8-alpine
    container_name: influxdb
    user: "1500:1500"
    mem_limit: 2G
    restart: unless-stopped
    ports:
      - 8086:8086
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    networks:
      - eseries_perf_analyzer
    volumes:
      - influxdb_data:/var/lib/influxdb
      # if you'd like to use in-directory volume, uncomment the following line
      # and then run: sudo chown -R 1500:1500 ./influx-database
      # - ./influx-database:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro

  utils:
    image: epa/utils:${TAG}
    container_name: utils
    mem_limit: 512M
    restart: unless-stopped
    build:
      context: ./utils
      args:
        BASE_IMAGE: influxdb:1.11.8-alpine
    networks:
      - eseries_perf_analyzer
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    command: ["tail","-f","/dev/null"]    

  grafana:
    image: grafana/grafana:8.5.27
    container_name: grafana
    mem_limit: 2G
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana_data:/var/lib/grafana
      - grafana_dashboards:/var/lib/grafana/dashboards
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    networks:
      - eseries_perf_analyzer

  grafana-init:
    image: epa/grafana-init:${TAG}
    build: 
      context: ./grafana-init
    container_name: grafana-init
    mem_limit: 128M
    depends_on:
      - grafana
    environment:
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_USER=admin
      - GRAFANA_PASSWORD=admin
      # Match the database name used by collector
      - DB_NAME=${DB_NAME:-eseries}
      # Optional: Create multiple datasources for different databases
      # - DB_LIST=eseries,epa1,custom
    networks:
      - eseries_perf_analyzer
    restart: "no"

  collector:
    image: epa/collector:${TAG}
    # image: docker.io/scaleoutsean/epa-collector:3.4.0 # best build your own
    container_name: collector
    build: ./collector
    mem_limit: 256m
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment: 
      - USERNAME=monitor
      - PASSWORD=monitor123
      - SYSNAME=R26U25-EF600
      - SYSID=600A098000F63714000000005E79C888
      - API=5.5.5.5
      - RETENTION_PERIOD=52w
      - DB_ADDRESS=6.6.6.6
      - DB_PORT=8086
      # Optional: Override default database name (eseries)
      # - DB_NAME=my_custom_db
      # Optional: Create database and exit (true/1 = enable)
      # - CREATE_DB=false
      # Optional: Only collect specific measurements (space-separated)
      # - INCLUDE=disks interface
      # - INCLUDE=power temp
    networks:
      - eseries_perf_analyzer

  collector-R24U04-E2824:
    image: epa/collector:${TAG}
    container_name: R24U04-E2824
    build: ./collector
    mem_limit: 256m
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment: 
      - USERNAME=monitor
      - PASSWORD=monitor123
      - SYSNAME=R24U04-E2824
      - SYSID=600A098000F63714000000005E79C999
      - API=7.7.7.7
      - RETENTION_PERIOD=52w
      - DB_ADDRESS=6.6.6.6
      - DB_PORT=8086
      # Example: Using custom database name for this collector
      # - DB_NAME=e2824_metrics
      # Optional: Only collect specific measurements (space-separated)
      # - INCLUDE=disks systems volumes
    networks:
      - eseries_perf_analyzer

networks:
  eseries_perf_analyzer:
    driver: bridge

volumes:
  influxdb_data:
  grafana_data:
  grafana_dashboards:
