services:

  influxdb:
    image: ${PROJ_NAME}/influxdb:${TAG}
    container_name: influxdb
    user: "1500:1500"
    mem_limit: 2G
    restart: unless-stopped
    ports:
      - 8086:8086
      # remove if InfluxDB doesn't need to be reachable from the outside (e.g. newer Grafana on external network)
      # if we only need to reach it from internal collector and/or Grafana in Docker, we can use http://inflxudb:8086
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    networks:
      - eseries_perf_analyzer
    volumes:
      - ./influx-database:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro

  utils:
    image: ${PROJ_NAME}/utils:${TAG}
    container_name: utils
    mem_limit: 512M
    restart: unless-stopped
    build:
      context: ./utils
      args:
        BASE_IMAGE: ${PROJ_NAME}/influxdb:${TAG}
    networks:
      - eseries_perf_analyzer
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    command: ["tail","-f","/dev/null"]    


  grafana:
    image: ${PROJ_NAME}/grafana:${TAG}
    container_name: grafana
    mem_limit: 2G
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - 3000:3000
        # exposes Grafana externally over HTTPS. it's recommended to use reverse proxy to protect Grafana, e.g.:
        # https://proxy.example.com:8443 -> http://grafana:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana_data:/var/lib/grafana
      - grafana_dashboards:/var/lib/grafana/dashboards  # R/W: User-created dashboards
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    networks:
      - eseries_perf_analyzer

  grafana-init:
    build: 
      context: ./grafana-init
      args:
        TAG: ${TAG}
        PROJ_NAME: ${PROJ_NAME}
    container_name: grafana-init
    mem_limit: 128M
    depends_on:
      - grafana
    environment:
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_USER=admin
      - GRAFANA_PASSWORD=admin
    networks:
      - eseries_perf_analyzer
    restart: "no"  # Run once and exit

  collector:
    image: epa/collector:${TAG}
    container_name: collector
    build: ./collector
    mem_limit: 64m
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment: 
      - USERNAME=monitor
      - PASSWORD=monitor123
      - SYSNAME=R26U25-EF600
      - SYSID=600A098000F63714000000005E79C888
      - API=5.5.5.5
      - RETENTION_PERIOD=52w
      - DB_ADDRESS=6.6.6.6
      - DB_PORT=8086
    networks:
      - eseries_perf_analyzer

  collector-R24U04-E2824:
    image: epa/collector:${TAG}
    container_name: R24U04-E2824
    build: ./collector
    mem_limit: 64m
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment: 
      - USERNAME=monitor
      - PASSWORD=monitor123
      - SYSNAME=R24U04-E2824
      - SYSID=600A098000F63714000000005E79C999
      - API=7.7.7.7
      - RETENTION_PERIOD=52w
      - DB_ADDRESS=6.6.6.6
      - DB_PORT=8086
    networks:
      - eseries_perf_analyzer

networks:
  eseries_perf_analyzer:
    external: true

volumes:
  grafana_data:
  grafana_dashboards:
