services:

  influxdb:
    image: influxdb:${CONTAINER_INFLUXDB_TAG}
    container_name: influxdb
    user: "1500:1500"
    mem_limit: 4G
    restart: unless-stopped
    ports:
      - 8086:8086      
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    networks:
      - eseries_perf_analyzer
    volumes:
      # Using bind mount to keep data in project directory (see SETUP.md for permissions)
      - ./data/influxdb:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      # Temporary mount for database restore
      # - ./dump:/dump:ro

  utils:
    image: epa/utils:${TAG}
    container_name: utils
    mem_limit: 512M
    restart: unless-stopped
    build:
      context: ./utils
      args:
        BASE_IMAGE: influxdb:${CONTAINER_INFLUXDB_TAG}
    networks:
      - eseries_perf_analyzer
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      # Temporary mount for database backup/restore
      # - ./dump:/dump
    command: ["tail","-f","/dev/null"]    

  grafana:
    image: grafana/grafana:${CONTAINER_GRAFANA_TAG}
    container_name: grafana
    mem_limit: 2G
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      # Using bind mounts to keep data in project directory (see SETUP.md for permissions)
      - ./data/grafana:/var/lib/grafana
      - ./data/grafana-dashboards:/var/lib/grafana/dashboards
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    networks:
      - eseries_perf_analyzer

  grafana-init:
    image: epa/grafana-init:${TAG}
    build: 
      context: ./grafana-init
    container_name: grafana-init
    mem_limit: 128M
    depends_on:
      - grafana
    environment:
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_USER=admin
      - GRAFANA_PASSWORD=admin
      # Match the database name used by collector
      - DB_NAME=${DB_NAME:-eseries}
      # Optional: Create multiple datasources for different databases
      # - DB_LIST=eseries,epa1,custom
    networks:
      - eseries_perf_analyzer
    restart: "no"

  collector:
    image: epa/collector:${TAG}
    # image: docker.io/scaleoutsean/epa-collector:${TAG} # best build your own
    container_name: collector
    build: ./collector
    mem_limit: 256m
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    # ports:
      # - 8080:8080  # Prometheus metrics endpoint (comment out if using --output influxdb only)
    environment: 
      - USERNAME=monitor
      - PASSWORD=monitor123
      - SYSNAME=EF600
      - SYSID=600A098000F63714000000005E79C888
      - API=5.5.5.5 7.7.7.7
      - RETENTION_PERIOD=8w
      - DB_ADDRESS=6.6.6.6
      - DB_PORT=8086      
      # Optional: Set output destination (both|influxdb|prometheus). Default: both. Prometheus port should be exposed to enable remote access.
      - OUTPUT=both
      # Optional: Set Prometheus port (default: 8080)
      - PROMETHEUS_PORT=8080
      # Optional: Override default database name (eseries)
      # - DB_NAME=my_custom_db
      # Optional: Create database and exit (true/1 = enable)
      # - CREATE_DB=false
      # Optional: Only collect specific measurements (space-separated)
      # - INCLUDE=disks interface
      # - INCLUDE=power temp
      # - INCLUDE=config_volumes volumes
    networks:
      - eseries_perf_analyzer

  collector-e4k:
    image: epa/collector:${TAG}
    container_name: collector-e4k
    build: ./collector
    mem_limit: 256m
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    # ports:
      # - 8081:8080  # Different host port for second collector's Prometheus endpoint in the same Docker Compose
    environment: 
      - USERNAME=monitor
      - PASSWORD=monitor123
      - SYSNAME=E4012
      - SYSID=600A098000F63714000000005E79C999
      - API=7.7.7.7
      - RETENTION_PERIOD=8w
      - DB_ADDRESS=6.6.6.6
      - DB_PORT=8086
      # Example: Using custom database name for this collector
      # - DB_NAME=e2824_metrics
      # Optional: Only collect specific measurements (space-separated)
      # - INCLUDE=disks systems volumes
      # - INCLUDE=config_volumes
      # Optional: Different output configuration for this collector
      - OUTPUT=influxdb  # Disable Prometheus
      # - PROMETHEUS_PORT=8080  # Container port (mapped to host 8081)
    networks:
      - eseries_perf_analyzer

networks:
  eseries_perf_analyzer:
    driver: bridge
