services:

  influxdb:
    image: ${PROJ_NAME}/influxdb:${TAG}
    container_name: influxdb
    mem_limit: 2G
    restart: unless-stopped
    ports:
      - 8086:8086
      # remove if InfluxDB doesn't need to be reachable from the outside (e.g. newer Grafana on external network)
      # we only need to reach it from internal Grafana in Docker, we can use http://inflxudb:8086
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    networks:
      - eseries_perf_analyzer
    volumes:
      - ./influx-database:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro

  utils:
    image: ${PROJ_NAME}/utils:latest
    container_name: utils
    mem_limit: 512M
    restart: unless-stopped
    build:
      context: ./utils
      args:
        BASE_IMAGE: ${PROJ_NAME}/influxdb:${TAG}
    networks:
      - eseries_perf_analyzer
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    command: ["tail","-f","/dev/null"]    


  grafana:
    image: ${PROJ_NAME}/grafana:${TAG}
    container_name: grafana
    mem_limit: 2G
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana_data:/var/lib/grafana
      - grafana_dashboards:/var/lib/grafana/dashboards  # R/W: User-created dashboards
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    networks:
      - eseries_perf_analyzer

  grafana-init:
    build: 
      context: ./grafana-init
      args:
        TAG: ${TAG}
        PROJ_NAME: ${PROJ_NAME}
    container_name: grafana-init
    mem_limit: 128M
    depends_on:
      - grafana
    environment:
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_USER=admin
      - GRAFANA_PASSWORD=admin
    networks:
      - eseries_perf_analyzer
    restart: "no"  # Run once and exit

networks:
  eseries_perf_analyzer:
    external: true

volumes:
  grafana_data:
  grafana_dashboards:
