{
 "title": "Configuration Template (Enhanced with Historical Data Support)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "storage_system",
    "label": "Storage System",
    "query": "SHOW TAG VALUES FROM \"config_drives\" WITH KEY = \"sys_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Host Configuration (Enhanced with Historical Data)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_host_name",
     "groupBy": [
      { "params": [ "hostRef" ], "type": "tag" }
     ],
     "measurement": "config_hosts",
     "select": [
      [
       { "params": [ "host_name_field" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Host Name" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "initiators_first_nodeName_ioInterfaceType"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Interface" ], "type": "alias" }
      ],
      [
       { "params": [ "hostSidePortCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Host Ports" ], "type": "alias" }
      ],
      [
       { "params": [ "isSAControlled" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SA Controlled" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "initiators_first_nodeName_remoteNodeWWN"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "FC_WWN" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "initiators_first_nodeName_iscsiNodeName"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "iSCSI_IQN" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "initiators_first_nodeName_nvmeNodeName"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "NVMe_NQN" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$storage_system$/" }
     ]
    },
    {
     "alias": "$tag_host_name",
     "groupBy": [
      { "params": [ "hostRef" ], "type": "tag" }
     ],
     "measurement": "config_hosts",
     "query": "SELECT last(\"host_name_field\") AS \"Host Name\", last(\"initiators_first_nodeName_ioInterfaceType\") AS \"Interface\", last(\"hostSidePortCount\") AS \"Host Ports\", last(\"isSAControlled\") AS \"SA Controlled\", last(\"initiators_first_nodeName_remoteNodeWWN\") AS \"FC_WWN\", last(\"initiators_first_nodeName_iscsiNodeName\") AS \"iSCSI_IQN\", last(\"initiators_first_nodeName_nvmeNodeName\") AS \"NVMe_NQN\" FROM \"pruned_retention\".\"config_hosts\" WHERE (\"sys_name\"::tag =~ /^$storage_system$/) AND $timeFilter AND time < now() - 1h GROUP BY \"hostRef\"",
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$storage_system$/" }
     ]
    }
   ]
  },
  {
   "title": "Drive Status (Enhanced with Historical Data)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "driveRef" ], "type": "tag" }
     ],
     "measurement": "config_drives",
     "select": [
      [
       { "params": [ "physicalLocation__trayRef" ], "type": "tag" },
       { "params": [ "Tray" ], "type": "alias" }
      ],
      [
       { "params": [ "physicalLocation_slot" ], "type": "tag" },
       { "params": [ "Slot" ], "type": "alias" }
      ],
      [
       { "params": [ "serialNumber" ], "type": "tag" },
       { "params": [ "Serial" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ],
      [
       { "params": [ "productID" ], "type": "tag" },
       { "params": [ "Model" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$storage_system$/" }
     ]
    },
    {
     "measurement": "config_drives",
     "query": "SELECT \"physicalLocation__trayRef\" AS \"Tray\", \"physicalLocation_slot\" AS \"Slot\", \"serialNumber\" AS \"Serial\", last(\"status\") AS \"Status\", \"productID\" AS \"Model\" FROM \"pruned_retention\".\"config_drives\" WHERE (\"sys_name\"::tag =~ /^$storage_system$/) AND $timeFilter AND time < now() - 1h GROUP BY \"driveRef\"",
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$storage_system$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Pools Configuration (Enhanced with Historical Data)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "volumeGroupRef" ], "type": "tag" }
     ],
     "measurement": "config_storage_pools",
     "select": [
      [
       { "params": [ "pool_name_field" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Pool Name" ], "type": "alias" }
      ],
      [
       { "params": [ "raidLevel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "RAID Level" ], "type": "alias" }
      ],
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "State" ], "type": "alias" }
      ],
      [
       { "params": [ "driveMediaType" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Media Type" ], "type": "alias" }
      ],
      [
       { "params": [ "usedSpace" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Used Space" ], "type": "alias" }
      ],
      [
       { "params": [ "freeSpace" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Free Space" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$storage_system$/" }
     ]
    },
    {
     "measurement": "config_storage_pools",
     "query": "SELECT last(\"pool_name_field\") AS \"Pool Name\", last(\"raidLevel\") AS \"RAID Level\", last(\"state\") AS \"State\", last(\"driveMediaType\") AS \"Media Type\", last(\"usedSpace\") AS \"Used Space\", last(\"freeSpace\") AS \"Free Space\" FROM \"pruned_retention\".\"config_storage_pools\" WHERE (\"sys_name\"::tag =~ /^$storage_system$/) AND $timeFilter AND time < now() - 1h GROUP BY \"volumeGroupRef\"",
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$storage_system$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume Configuration (Enhanced with Historical Data)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "volumeRef" ], "type": "tag" }
     ],
     "measurement": "config_volumes",
     "select": [
      [
       { "params": [ "volume_name_field" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Volume Name" ], "type": "alias" }
      ],
      [
       { "params": [ "capacity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Capacity" ], "type": "alias" }
      ],
      [
       { "params": [ "listOfMappings_lun" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "LUN" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$storage_system$/" }
     ]
    },
    {
     "measurement": "config_volumes",
     "query": "SELECT last(\"volume_name_field\") AS \"Volume Name\", last(\"capacity\") AS \"Capacity\", last(\"listOfMappings_lun\") AS \"LUN\" FROM \"pruned_retention\".\"config_volumes\" WHERE (\"sys_name\"::tag =~ /^$storage_system$/) AND $timeFilter AND time < now() - 1h GROUP BY \"volumeRef\"",
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$storage_system$/" }
     ]
    }
   ]
  }
 ]
}