{
 "title": "Disk View Dashboard",
 "tags": [ "NetAppESeries" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "System",
    "label": "System",
    "query": "SHOW TAG VALUES FROM \"disks\" WITH KEY = \"sys_name\""
   },
   {
    "name": "VolumeGroup",
    "label": "Volume Group",
    "query": "SHOW TAG VALUES FROM disks WITH KEY = \"vol_group_name\" WHERE \"sys_name\" =~ /$System/"
   },
   {
    "name": "Tray",
    "label": "Tray",
    "query": "SHOW TAG VALUES FROM disks WITH KEY = \"sys_tray\" WHERE \"sys_name\" =~ /$System/ AND \"vol_group_name\" =~ /$VolumeGroup/"
   },
   {
    "name": "Slot",
    "label": "Slot",
    "query": "SHOW TAG VALUES FROM disks WITH KEY = \"sys_tray_slot\" WHERE \"sys_name\" =~ /$System/ AND \"vol_group_name\" =~ /$VolumeGroup/ AND \"sys_tray\" =~ /$Tray/"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "sys_tray::tag" ], "type": "tag" },
      { "params": [ "sys_tray_slot::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"combinedResponseTime\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\" =~ /^$Tray$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "combinedResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"ds_combinedResponseTime\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\"::tag =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\"::tag =~ /^$Tray$/ AND \"sys_tray_slot\"::tag =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\"::tag, \"sys_tray\"::tag, \"sys_tray_slot\"::tag fill(none)",
     "select": [
      [
       { "params": [ "combinedResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "sys_tray::tag" ], "type": "tag" },
      { "params": [ "sys_tray_slot::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"combinedThroughput\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "combinedThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"ds_combinedThroughput\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\"::tag =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\"::tag =~ /^$Tray$/ AND \"sys_tray_slot\"::tag =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\"::tag, \"sys_tray\"::tag, \"sys_tray_slot\"::tag fill(none)",
     "select": [
      [
       { "params": [ "combinedThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Total IOPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "sys_tray::tag" ], "type": "tag" },
      { "params": [ "sys_tray_slot::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"combinedIOps\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "combinedIOps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"ds_combinedIOps\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\"::tag =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\"::tag =~ /^$Tray$/ AND \"sys_tray_slot\"::tag =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\"::tag, \"sys_tray\"::tag, \"sys_tray_slot\"::tag fill(none)",
     "select": [
      [
       { "params": [ "combinedIOps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "sys_tray::tag" ], "type": "tag" },
      { "params": [ "sys_tray_slot::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"readResponseTime\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "readResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"ds_readResponseTime\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\"::tag =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\"::tag =~ /^$Tray$/ AND \"sys_tray_slot\"::tag =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\"::tag, \"sys_tray\"::tag, \"sys_tray_slot\"::tag fill(none)",
     "select": [
      [
       { "params": [ "readResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Read Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "sys_tray::tag" ], "type": "tag" },
      { "params": [ "sys_tray_slot::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"readThroughput\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "readThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"ds_readThroughput\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\"::tag =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\"::tag =~ /^$Tray$/ AND \"sys_tray_slot\"::tag =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\"::tag, \"sys_tray\"::tag, \"sys_tray_slot\"::tag fill(none)",
     "select": [
      [
       { "params": [ "readThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Read IOPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "sys_tray::tag" ], "type": "tag" },
      { "params": [ "sys_tray_slot::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"readIOps\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "readIOps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"ds_readIOps\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\"::tag =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\"::tag =~ /^$Tray$/ AND \"sys_tray_slot\"::tag =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\"::tag, \"sys_tray\"::tag, \"sys_tray_slot\"::tag fill(none)",
     "select": [
      [
       { "params": [ "readIOps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "sys_tray::tag" ], "type": "tag" },
      { "params": [ "sys_tray_slot::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"writeResponseTime\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "writeResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"ds_writeResponseTime\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\"::tag =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\"::tag =~ /^$Tray$/ AND \"sys_tray_slot\"::tag =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\"::tag, \"sys_tray\"::tag, \"sys_tray_slot\"::tag fill(none)",
     "select": [
      [
       { "params": [ "writeResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Write Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "sys_tray::tag" ], "type": "tag" },
      { "params": [ "sys_tray_slot::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "writeThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"writeThroughput\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\"::tag =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\"::tag =~ /^$Tray$/ AND \"sys_tray_slot\"::tag =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\"::tag, \"sys_tray\"::tag, \"sys_tray_slot\"::tag fill(none)",
     "select": [
      [
       { "params": [ "writeThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Write IOPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "sys_tray::tag" ], "type": "tag" },
      { "params": [ "sys_tray_slot::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "writeIOps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: Tray $tag_sys_tray - Slot $tag_sys_tray_slot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"ds_writeIOps\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\"::tag =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\"::tag =~ /^$Tray$/ AND \"sys_tray_slot\"::tag =~ /^$Slot$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\"::tag, \"sys_tray\"::tag, \"sys_tray_slot\"::tag fill(none)",
     "select": [
      [
       { "params": [ "writeIOps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "sys_tray::tag", "operator": "=~", "value": "/^$Tray$/" },
      { "condition": "AND", "key": "sys_tray_slot::tag", "operator": "=~", "value": "/^$Slot$/" }
     ]
    }
   ]
  },
  {
   "title": "SSD spare blocks remaining %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT last(\"spareBlocksRemainingPercent\") FROM \"disks\" WHERE (\"sys_name\"::tag =~ /^$System$/ AND \"vol_group_name\" =~ /^$VolumeGroup$/ AND \"sys_tray\"::tag =~ /^$Tray$/ AND \"sys_tray_slot\"::tag =~ /^$Slot$/) AND $timeFilter GROUP BY \"sys_name\"::tag, \"sys_tray\"::tag, \"sys_tray_slot\"::tag fill(none)",
     "select": [
      [
       { "params": [ "spareBlocksRemainingPercent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}