{
 "title": "System View Dashboard",
 "tags": [ "NetAppESeries" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "System",
    "label": "System",
    "query": "SHOW TAG VALUES FROM \"systems\" WITH KEY = \"sys_name\""
   }
  ]
 },
 "panels": [
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disks",
   "type": "table",
   "description": "List of disks on the selected system(s)",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sys_tray_slot" ], "type": "tag" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "sys_tray" ], "type": "tag" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "readOps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"combinedResponseTime\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/) AND $timeFilter GROUP BY time($__interval), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "combinedResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    },
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT mean(\"ds_combinedResponseTime\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\" =~ /^$System$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "combinedResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "combinedThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    },
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT sum(\"ds_combinedThroughput\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\" =~ /^$System$/) AND $timeFilter AND time < now() - 1w GROUP BY time(5s), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "combinedThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "combinedIOps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    },
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disks",
     "query": "SELECT sum(\"ds_combinedIOps\") FROM \"downsample_retention\".\"disks\" WHERE (\"sys_name\" =~ /^$System$/) AND $timeFilter AND time < now() - 1w GROUP BY time(5s), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "combinedIOps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  { "title": "Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Volumes",
   "type": "table",
   "description": "List of volumes on the selected system(s)",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vol_name" ], "type": "tag" },
      { "params": [ "sys_name" ], "type": "tag" }
     ],
     "measurement": "volumes",
     "select": [
      [
       { "params": [ "readOps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Volume Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "select": [
      [
       { "params": [ "combinedResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    },
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"ds_combinedResponseTime\") FROM \"downsample_retention\".\"volumes\" WHERE (\"sys_name\" =~ /^$System$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "combinedResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Volume Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "select": [
      [
       { "params": [ "combinedThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    },
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT sum(\"ds_combinedThroughput\") FROM \"downsample_retention\".\"volumes\" WHERE (\"sys_name\" =~ /^$System$/) AND $timeFilter AND time < now() - 1w GROUP BY time(5s), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "combinedThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Volume IOps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT sum(\"combinedIOps\") FROM \"default_retention\".\"volumes\" WHERE (\"sys_name\" =~ /^$System$/) AND $timeFilter GROUP BY time(5s), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "combinedIOps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    },
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT sum(\"ds_combinedIOps\") FROM \"downsample_retention\".\"volumes\" WHERE (\"sys_name\" =~ /^$System$/) AND $timeFilter AND time < now() - 1w GROUP BY time(5s), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "combinedIOps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Average CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "systems",
     "query": "SELECT \"cpuAvgUtilization\" FROM \"systems\" WHERE $timeFilter GROUP BY time($__interval), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "cpuAvgUtilization" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    },
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "systems",
     "query": "SELECT last(\"ds_cpuAvgUtilization\") FROM \"downsample_retention\".\"systems\" WHERE (\"sys_name\" =~ /^$System$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\" fill(none)",
     "select": [
      [
       { "params": [ "cpuAvgUtilization" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Maximum CPU Utilization",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 19 },
   "targets": [
    {
     "alias": "$tag_sys_name",
     "groupBy": [
      { "params": [ "sys_name" ], "type": "tag" }
     ],
     "measurement": "systems",
     "select": [
      [
       { "params": [ "maxCpuUtilization" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "Major Event Log",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 29 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sys_name" ], "type": "tag" }
     ],
     "measurement": "major_event_log",
     "query": "SELECT \"id\", \"location\", \"description\" FROM \"major_event_log\" WHERE (\"sys_name\" =~ /^$System$/) GROUP BY \"sys_name\"",
     "select": [
      [
       { "params": [ "id" ], "type": "field" }
      ],
      [
       { "params": [ "location" ], "type": "field" }
      ],
      [
       { "params": [ "description" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  },
  {
   "title": "System Failures",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 29 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "failure_type" ], "type": "tag" },
      { "params": [ "object_type" ], "type": "tag" }
     ],
     "measurement": "failures",
     "query": "SELECT * FROM (SELECT last(\"name_of\"),active FROM \"failures\" WHERE (\"sys_name\" =~ /^$System$/) AND $timeFilter GROUP BY \"sys_name\", \"failure_type\", \"object_type\") WHERE (\"active\" = 'True')",
     "select": [
      [
       { "params": [ "name_of" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "active", "operator": "=", "value": "True" }
     ]
    }
   ]
  }
 ]
}