{
 "title": "Volume View Dashboard",
 "tags": [ "NetAppESeries" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "System",
    "label": "System",
    "query": "SHOW TAG VALUES FROM \"volumes\" WITH KEY = \"sys_name\""
   },
   {
    "name": "Volume",
    "label": "Volume",
    "query": "SHOW TAG VALUES FROM volumes WITH KEY = \"vol_name\" WHERE \"sys_name\" =~ /$System/"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "vol_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"combinedResponseTime\") FROM \"volumes\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_name\" =~ /^$Volume$/) AND $timeFilter GROUP BY time($__interval), \"sys_name\", \"vol_name\" fill(none)",
     "select": [
      [
       { "params": [ "combinedResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"ds_combinedResponseTime\") FROM \"downsample_retention\".\"volumes\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_name\" =~ /^$Volume$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\", \"vol_name\" fill(none)",
     "select": [
      [
       { "params": [ "combinedResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "vol_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"combinedThroughput\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "combinedThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"ds_combinedThroughput\") FROM \"downsample_retention\".\"volumes\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_name\" =~ /^$Volume$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\", \"vol_name\" fill(none)",
     "select": [
      [
       { "params": [ "combinedThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Total IOPs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "vol_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"combinedIOps\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "combinedIOps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"ds_combinedIOps\") FROM \"downsample_retention\".\"volumes\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_name\" =~ /^$Volume$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\", \"vol_name\" fill(none)",
     "select": [
      [
       { "params": [ "combinedIOps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "vol_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"readResponseTime\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "readResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"ds_readResponseTime\") FROM \"downsample_retention\".\"volumes\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_name\" =~ /^$Volume$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\", \"vol_name\" fill(none)",
     "select": [
      [
       { "params": [ "readResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "vol_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"readThroughput\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "readThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"ds_readThroughput\") FROM \"downsample_retention\".\"volumes\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_name\" =~ /^$Volume$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\", \"vol_name\" fill(none)",
     "select": [
      [
       { "params": [ "readThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Read IOPs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "vol_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"readIOps\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "readIOps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"ds_readIOps\") FROM \"downsample_retention\".\"volumes\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_name\" =~ /^$Volume$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\", \"vol_name\" fill(none)",
     "select": [
      [
       { "params": [ "readIOps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "vol_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"writeResponseTime\") FROM \"disks\" WHERE (\"sys_name\" =~ /^$System$/ AND \"sys_tray\" =~ /^$Tray$/ AND \"sys_tray_slot\" =~ /^$Slot$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "writeResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"ds_writeResponseTime\") FROM \"downsample_retention\".\"volumes\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_name\" =~ /^$Volume$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\", \"vol_name\" fill(none)",
     "select": [
      [
       { "params": [ "writeResponseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "vol_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"writeThroughput\") FROM \"volumes\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_name\" =~ /^$Volume$/) AND $timeFilter GROUP BY time($__interval), \"sys_name\", \"vol_name\" fill(none)",
     "select": [
      [
       { "params": [ "writeThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"ds_writeThroughput\") FROM \"downsample_retention\".\"volumes\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_name\" =~ /^$Volume$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\", \"vol_name\" fill(none)",
     "select": [
      [
       { "params": [ "writeThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Write IOPs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "vol_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "select": [
      [
       { "params": [ "writeIOps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    },
    {
     "alias": "$tag_sys_name: $tag_vol_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "query": "SELECT mean(\"ds_writeIOps\") FROM \"downsample_retention\".\"volumes\" WHERE (\"sys_name\" =~ /^$System$/ AND \"vol_name\" =~ /^$Volume$/) AND $timeFilter AND time < now() - 1w GROUP BY time($__interval), \"sys_name\", \"vol_name\" fill(none)",
     "select": [
      [
       { "params": [ "writeIOps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_name", "operator": "=~", "value": "/^$System$/" },
      { "condition": "AND", "key": "vol_name", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume SSD Cache Hit Rate",
   "type": "timeseries",
   "description": "Available on only Hybrid E-Series arrays with SSD Flash Cache enabled for NL-SAS volumes. Delete this panel if you don't have such hardware configuration.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "repeat": "System",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vol_name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "select": [
      [
       { "params": [ "flashCacheHitPct" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vol_name::tag", "operator": "=~", "value": "/^$Volume$/" },
      { "condition": "AND", "key": "sys_name::tag", "operator": "=~", "value": "/^$System$/" }
     ]
    }
   ]
  }
 ]
}