version: '3.6'

services:

  collector-dbmanager:
    image: epa/dbmanager:v3.3.0
    build:
          context: .
          dockerfile: ./dbmanager/Dockerfile
    mem_limit: 32m
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment: 
      - RETENTION_PERIOD=52w
      - DB_ADDRESS=6.6.6.6
      - DB_PORT=8086

  collector-R26U25-EF600:
    image: epa/collector:v3.3.0
    container_name: R26U25-EF600
    build: ./collector
    mem_limit: 64m
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment: 
      - USERNAME=monitor
      - PASSWORD=monitor123
      - SYSNAME=R26U25-EF600
      - SYSID=600A098000F63714000000005E79C888
      - API=5.5.5.5
      - RETENTION_PERIOD=52w
      - DB_ADDRESS=6.6.6.6
      - DB_PORT=8086

  collector-R24U04-E2824:
    image: epa/collector:v3.3.0
    container_name: R24U04-E2824
    mem_limit: 64m
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment: 
      - USERNAME=monitor
      - PASSWORD=monitor123
      - SYSNAME=R24U04-E2824
      - SYSID=600A098000F63714000000005E79C999
      - API=7.7.7.7
      - RETENTION_PERIOD=52w
      - DB_ADDRESS=6.6.6.6
      - DB_PORT=8086
